### ISSUE TITLE
Decoding CAT21

### ISSUE THREAD

**Issue by drumlight** [filipjonckers/asterix4py#1]
I'm still trying to work through the problem but it's almost the end of the week and I'll need to pick up again on Monday to improve my understanding of the issue. 

Compound data items such as I021/295, Data Ages are failing to decode. The indicator_octets don't seem to be loaded from the correct place in the buffer and it then seems to map the bits to uapitem ids.

I've attached a couple of sample messages and their source pcap file as the asterix Wireshark dissector appears to decode them correctly.
[asterix.zip](https://github.com/filipjonckers/asterix4py/files/5211094/asterix.zip)

**Comment by drumlight** [comment]
My apologies, I think this error was because my messages are a later edition of CAT21 and a third extension was added to I021/090, Quality Indicators. When this extension was skipped the bytes pointer was left out of sync so I'm going to try creating a new xml file and will try to resolve my problem that way.

**Comment by filipjonckers** [comment]
@drumlight  Thanks for contributing !
You indeed need to make sure that you use the correct version of an Asterix category - especially cat21
The original library contained quite a few decoder bugs which were fixed here but there could be more of course.
Currently I can only verify cat48 and cat62.
